[package]
name = "sharp-service"
version.workspace = true
edition.workspace = true

[dependencies]
alloy.workspace = true
async-trait.workspace = true
base64 = "0.22.1"
cairo-vm.workspace = true
color-eyre.workspace = true
dotenvy.workspace = true
gps-fact-checker.workspace = true
hex.workspace = true
httpmock.workspace = true
lazy_static.workspace = true
log.workspace = true
prover-client-interface.workspace = true
reqwest.workspace = true
rstest.workspace = true
serde.workspace = true
serde_json.workspace = true
snos.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
utils.workspace = true
uuid.workspace = true

#Instrumentation
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
opentelemetry = { workspace = true, features = ["metrics", "logs"] }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio", "logs"] }
opentelemetry-otlp = { workspace = true, features = [
  "tonic",
  "metrics",
  "logs",
] }
opentelemetry-semantic-conventions = { workspace = true }
opentelemetry-appender-tracing = { workspace = true, default-features = false }
tracing-core = { workspace = true, default-features = false }
tracing-opentelemetry = "0.26.0"


[dev-dependencies]
tokio.workspace = true
httpmock.workspace = true
