[workspace]
resolver = "2"
members = [
  "crates/orchestrator",
  "crates/da-clients/da-client-interface",
  "crates/da-clients/ethereum",
  "crates/prover-clients/prover-client-interface",
  "crates/prover-clients/gps-fact-checker",
  "crates/prover-clients/sharp-service",
  "crates/prover-clients/atlantic-service",
  "crates/utils",
  "crates/settlement-clients/settlement-client-interface",
  "crates/settlement-clients/ethereum",
  "crates/settlement-clients/starknet",
  "e2e-tests",
]
exclude = ["madara-bootstrapper", "pathfinder", "madara"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Apoorv Sadana <@apoorvsadana>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
num = { version = "0.4.1" }
async-trait = { version = "0.1.77" }
alloy = { version = "0.2.1", features = [
  "full",
  "node-bindings",
  "rpc-types-debug",
  "rpc-types-trace",
  "json-rpc",
  "rpc-client",
] }
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-s3 = { version = "1.38.0", features = ["behavior-version-latest"] }
aws-sdk-eventbridge = { version = "1.41.0", features = [
  "behavior-version-latest",
] }
aws-sdk-sqs = "1.36.0"
axum = { version = "0.7.4" }
axum-macros = "0.4.1"
bincode = "1.3.3"
bytes = "1.6.0"
color-eyre = "0.6.2"
chrono = "0.4.0"
c-kzg = "1.0.3"
dotenvy = "0.15.7"
futures = "0.3.30"
log = "0.4.21"
mongodb = { version = "2.8.1", features = ["bson-chrono-0_4"] }
omniqueue = { version = "0.2.0" }
reqwest = { version = "0.12.7", features = [
  "rustls-tls",
  "native-tls",
  "json",
  "multipart",
  "stream",
] }
rstest = "0.22.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
starknet = "0.11.0"
tempfile = "3.12.0"
thiserror = "1.0.57"
tokio = { version = "1.37.0" }
tokio-stream = "0.1.15"
tokio-util = "0.7.11"
url = { version = "2.5.0", features = ["serde"] }
uuid = { version = "1.7.0", features = ["v4", "serde"] }
httpmock = { version = "0.7.0", features = ["remote"] }
num-bigint = { version = "0.4.4" }
num-traits = "0.2"
lazy_static = "1.4.0"
stark_evm_adapter = "0.1.1"
hex = "0.4"
itertools = "0.13.0"
mockall = "0.13.0"
testcontainers = "0.18.0"
once_cell = "1.8"
appchain-core-contract-client = { git = "https://github.com/byteZorvin/zaun", branch = "type-update" }
crypto-bigint = { version = "0.5.5" }
env_logger = "0.11.5"
strum_macros = "0.26.4"
strum = "0.26.3"


# Instrumentation
opentelemetry = { version = "0.25.0", features = ["metrics", "logs"] }
opentelemetry_sdk = { version = "0.25.0", features = ["rt-tokio", "logs"] }
opentelemetry-stdout = { version = "0.25.0" }
opentelemetry-otlp = { version = "0.25.0", features = [
  "tonic",
  "metrics",
  "logs",
] }
opentelemetry-semantic-conventions = { version = "0.25.0" }
opentelemetry-appender-tracing = { version = "0.25.0", default-features = false }
tracing = { version = "0.1.40", default-features = false }
tracing-core = { version = "0.1.32", default-features = false }
tracing-subscriber = { version = "0.3.18", features = [
  "env-filter",
  "registry",
  "std",
] }
tracing-opentelemetry = "0.26.0"

# Cairo VM
cairo-vm = { git = "https://github.com/Moonsong-Labs/cairo-vm", branch = "herman/fix-pie-serialization", features = [
  "cairo-1-hints",
  "extensive_hints",
  "mod_builtin",
] }

# Snos & Sharp (Starkware)
# TODO: need to update this once the updated PR merges
starknet-os = { git = "https://github.com/Mohiiit/snos", rev = "2dcd3b0f0c6bfa368a802de12de29cd124c72bb8" }
prove_block = { git = "https://github.com/Mohiiit/snos", rev = "2dcd3b0f0c6bfa368a802de12de29cd124c72bb8" }


# Madara prover API
madara-prover-common = { git = "https://github.com/Moonsong-Labs/madara-prover-api", branch = "od/use-latest-cairo-vm" }
madara-prover-rpc-client = { git = "https://github.com/Moonsong-Labs/madara-prover-api", branch = "od/use-latest-cairo-vm" }

# Project
da-client-interface = { path = "crates/da-clients/da-client-interface" }
ethereum-da-client = { path = "crates/da-clients/ethereum" }

settlement-client-interface = { path = "crates/settlement-clients/settlement-client-interface" }
ethereum-settlement-client = { path = "crates/settlement-clients/ethereum" }
starknet-settlement-client = { path = "crates/settlement-clients/starknet" }

utils = { path = "crates/utils" }
prover-client-interface = { path = "crates/prover-clients/prover-client-interface" }
gps-fact-checker = { path = "crates/prover-clients/gps-fact-checker" }
sharp-service = { path = "crates/prover-clients/sharp-service" }
atlantic-service = { path = "crates/prover-clients/atlantic-service" }
orchestrator = { path = "crates/orchestrator" }
