services:
  app:
    build: .
    ports:
      - "${MADARA_ORCHESTRATOR_PORT}:3000"
    environment:
      - MADARA_ORCHESTRATOR_HOST=${MADARA_ORCHESTRATOR_HOST:-127.0.0.1}
      - MADARA_ORCHESTRATOR_PORT=${MADARA_ORCHESTRATOR_PORT:-3000}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-localhost}
      - DATA_STORAGE=${DATA_STORAGE:-s3}
      - MADARA_ORCHESTRATOR_AWS_S3_BUCKET_NAME=${MADARA_ORCHESTRATOR_AWS_S3_BUCKET_NAME}
      - QUEUE_PROVIDER=${QUEUE_PROVIDER:-sqs}
      - SQS_SNOS_JOB_PROCESSING_QUEUE_URL=${SQS_SNOS_JOB_PROCESSING_QUEUE_URL}
      - SQS_SNOS_JOB_VERIFICATION_QUEUE_URL=${SQS_SNOS_JOB_VERIFICATION_QUEUE_URL}
      - SQS_DATA_SUBMISSION_JOB_PROCESSING_QUEUE_URL=${SQS_DATA_SUBMISSION_JOB_PROCESSING_QUEUE_URL}
      - SQS_DATA_SUBMISSION_JOB_VERIFICATION_QUEUE_URL=${SQS_DATA_SUBMISSION_JOB_VERIFICATION_QUEUE_URL}
      - SQS_PROOF_REGISTRATION_JOB_PROCESSING_QUEUE_URL=${SQS_PROOF_REGISTRATION_JOB_PROCESSING_QUEUE_URL}
      - SQS_PROOF_REGISTRATION_JOB_VERIFICATION_QUEUE_URL=${SQS_PROOF_REGISTRATION_JOB_VERIFICATION_QUEUE_URL}
      - SQS_PROVING_JOB_PROCESSING_QUEUE_URL=${SQS_PROVING_JOB_PROCESSING_QUEUE_URL}
      - SQS_PROVING_JOB_VERIFICATION_QUEUE_URL=${SQS_PROVING_JOB_VERIFICATION_QUEUE_URL}
      - SQS_UPDATE_STATE_JOB_PROCESSING_QUEUE_URL=${SQS_UPDATE_STATE_JOB_PROCESSING_QUEUE_URL}
      - SQS_UPDATE_STATE_JOB_VERIFICATION_QUEUE_URL=${SQS_UPDATE_STATE_JOB_VERIFICATION_QUEUE_URL}
      - SQS_JOB_HANDLE_FAILURE_QUEUE_URL=${SQS_JOB_HANDLE_FAILURE_QUEUE_URL}
      - SQS_WORKER_TRIGGER_QUEUE_URL=${SQS_WORKER_TRIGGER_QUEUE_URL}
      - ALERTS=${ALERTS:-sns}
      - MADARA_ORCHESTRATOR_AWS_SNS_ARN=${MADARA_ORCHESTRATOR_AWS_SNS_ARN}
      - MADARA_ORCHESTRATOR_AWS_SNS_ARN=${MADARA_ORCHESTRATOR_AWS_SNS_ARN}
      - DATABASE=${DATABASE:-mongodb}
      - MADARA_ORCHESTRATOR_MONGODB_CONNECTION_URL=${MADARA_ORCHESTRATOR_MONGODB_CONNECTION_URL}
      - PROVER_SERVICE=${PROVER_SERVICE:-sharp}
      - MADARA_ORCHESTRATOR_SHARP_CUSTOMER_ID=${MADARA_ORCHESTRATOR_SHARP_CUSTOMER_ID}
      - MADARA_ORCHESTRATOR_SHARP_URL=${MADARA_ORCHESTRATOR_SHARP_URL}
      - MADARA_ORCHESTRATOR_SHARP_USER_CRT=${MADARA_ORCHESTRATOR_SHARP_USER_CRT}
      - MADARA_ORCHESTRATOR_SHARP_USER_KEY=${MADARA_ORCHESTRATOR_SHARP_USER_KEY}
      - MADARA_ORCHESTRATOR_SHARP_SERVER_CRT=${MADARA_ORCHESTRATOR_SHARP_SERVER_CRT}
      - MADARA_ORCHESTRATOR_SHARP_PROOF_LAYOUT=${MADARA_ORCHESTRATOR_SHARP_PROOF_LAYOUT:-small}
      - DA_LAYER=${DA_LAYER:-ethereum}
      - SETTLEMENT_LAYER=${SETTLEMENT_LAYER:-ethereum}
      - MADARA_ORCHESTRATOR_ETHEREUM_SETTLEMENT_RPC_URL=${MADARA_ORCHESTRATOR_ETHEREUM_SETTLEMENT_RPC_URL}
      - MADARA_ORCHESTRATOR_MADARA_RPC_URL=${MADARA_ORCHESTRATOR_MADARA_RPC_URL}
      - MEMORY_PAGES_CONTRACT_ADDRESS=${MEMORY_PAGES_CONTRACT_ADDRESS}
      - MADARA_ORCHESTRATOR_ETHEREUM_PRIVATE_KEY=${MADARA_ORCHESTRATOR_ETHEREUM_PRIVATE_KEY}
      - MADARA_ORCHESTRATOR_L1_CORE_CONTRACT_ADDRESS=${MADARA_ORCHESTRATOR_L1_CORE_CONTRACT_ADDRESS}
      - MADARA_ORCHESTRATOR_RPC_FOR_SNOS=${MADARA_ORCHESTRATOR_RPC_FOR_SNOS}
      - MADARA_ORCHESTRATOR_STARKNET_PRIVATE_KEY=${MADARA_ORCHESTRATOR_STARKNET_PRIVATE_KEY}
      - MADARA_ORCHESTRATOR_STARKNET_ACCOUNT_ADDRESS=${MADARA_ORCHESTRATOR_STARKNET_ACCOUNT_ADDRESS}
      - MADARA_ORCHESTRATOR_MADARA_BINARY_PATH=${MADARA_ORCHESTRATOR_MADARA_BINARY_PATH}
      - MADARA_ORCHESTRATOR_OTEL_SERVICE_NAME=${MADARA_ORCHESTRATOR_OTEL_SERVICE_NAME:-madara_orchestrator}
      - MADARA_ORCHESTRATOR_OTEL_COLLECTOR_ENDPOINT=${MADARA_ORCHESTRATOR_OTEL_COLLECTOR_ENDPOINT}
      - TRACING_LEVEL=${TRACING_LEVEL:-info}
      - MADARA_ORCHESTRATOR_STARKNET_OPERATOR_ADDRESS=${MADARA_ORCHESTRATOR_STARKNET_OPERATOR_ADDRESS}
    depends_on:
      - mongodb
      - localstack
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
