services:
  snos:
    build:
      context: .
      dockerfile: Dockerfile.snos
    volumes:
      - ../snos:/snos
    command: bash -c "source ./setup-scripts/setup-cairo.sh && ./setup-scripts/reset-tests.sh"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    depends_on:
      snos:
        condition: service_completed_successfully

  localstack:
    image: localstack/localstack@sha256:763947722c6c8d33d5fbf7e8d52b4bddec5be35274a0998fdc6176d733375314
    ports:
      - "4566:4566"
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_started

  mock-prover:
    image: ocdbytes/mock-prover:latest
    ports:
      - "6000:6000"
    container_name: mock-prover
    depends_on:
      localstack:
        condition: service_started

  pathfinder:
    build:
      context: .
      dockerfile: Dockerfile.pathfinder
    volumes:
      - ../pathfinder:/pathfinder
    environment:
      - PATHFINDER_FORCE_VERSION=1
    ports:
      - "9545:9545"
    command: bash -c "cargo run --bin pathfinder -- --network custom --chain-id MADARA_DEVNET --ethereum.url wss://eth-sepolia.g.alchemy.com/v2/WIUR5JUZXieEBkze6Xs3IOXWhsS840TX --gateway-url http://localhost:8080/gateway --feeder-gateway-url http://localhost:8080/feeder_gateway --storage.state-tries archive --data-directory /pathfinder/data --http-rpc 127.0.0.1:9545"
  depends_on:
    mock-prover:
      condition: service_started

  anvil:
    build:
      context: .
      dockerfile: Dockerfile.anvil
    ports:
      - "8545:8545"
    command: /bin/bash -c "anvil --block-time 1"
    depends_on:
      pathfinder:
        condition: service_started
