[package]
name = "ethereum-settlement-client"
version.workspace = true
edition.workspace = true

[dependencies]
alloy = { workspace = true, features = ["full", "node-bindings"] }
alloy-primitives = { version = "0.7.7", default-features = false }
async-trait = { workspace = true }
c-kzg = "1.0.0"
color-eyre = { workspace = true }
dotenv = "0.15"
dotenvy = { workspace = true }
lazy_static = "1.4.0"
mockall = "0.12.1"
reqwest = { version = "0.12.3" }
rstest = { workspace = true }
serde = { version = "1.0.196", default-features = false, features = ["derive"] }
settlement-client-interface = { workspace = true }
snos = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
utils = { workspace = true }

[dev-dependencies]
tokio-test = "*"
