[package]
name = "ethereum-settlement-client"
version.workspace = true
edition.workspace = true

[dependencies]
alloy-primitives = { version = "0.7.7", default-features = false }

alloy = { workspace = true, features = ["full", "node-bindings"] }
async-trait = { workspace = true }
c-kzg = { workspace = true }
cairo-vm = { workspace = true }
color-eyre = { workspace = true }
dotenvy = { workspace = true }
lazy_static = { workspace = true }
log.workspace = true
mockall = { workspace = true }
reqwest = { workspace = true }
rstest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
settlement-client-interface = { workspace = true }
starknet-os = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
utils = { workspace = true }

[dev-dependencies]
tokio-test = "*"

[features]
testing = []
