name: Rust Test & Coverage

on:
  workflow_call:
    secrets:
      ETHEREUM_BLAST_RPC_URL:
        required: true

jobs:
  coverage:
    runs-on: karnot-arc-runner-set

    services:
      localstack:
        image: localstack/localstack
        env:
          SERVICES: s3, sqs, sns
          DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID"
          AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY"
        ports:
          - 4566:4566
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3

      - name: Install necessary deps
        run: |
          sudo apt update
          sudo apt install -y gcc g++ build-essential libssl-dev pkg-config curl wget git

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # - name: Rust Cache
      #   uses: Swatinem/rust-cache@v2

      - uses: sparebank1utvikling/actions-cache-s3@main
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          aws-s3-bucket: ${{secrets.AWS_S3_BUCKET_NAME}}
          aws-region: us-east-1

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Check Anvil Installation
        run: |
          if command -v anvil &> /dev/null
          then
              echo "Anvil is installed. Version information:"
              anvil --version
          else
              echo "Anvil is not installed or not in PATH"
              exit 1
          fi

      - name: Install cargo-llvm-cov & nextest
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Getting neccesary files for testing
        run: |
          wget -P ./crates/prover-services/sharp-service/tests/artifacts https://madara-orchestrator-sharp-pie.s3.amazonaws.com/238996-SN.zip

      - name: Run llvm-cov tests
        env:
          ETHEREUM_BLAST_RPC_URL: ${{ secrets.ETHEREUM_BLAST_RPC_URL }}
        run: RUST_LOG=debug RUST_BACKTRACE=1 cargo llvm-cov nextest --release --features testing --lcov --output-path lcov.info --test-threads=1 --workspace --exclude=e2e-tests

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          files: lcov.info
          debug: true
