---
name: Task - Rust Tests & Coverage

on:
  pull_request_target:
    branches:
      - main
    types: [opened, synchronize, reopened]
  push:
    branches-ignore:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  coverage:
    # sadly, for now we have to "rebuild" for the coverage
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack
        env:
          SERVICES: s3, sqs
          DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID"
          AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY"
        ports:
          - 4566:4566
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3

      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as the cache uses the current rustc version as its cache key
      - run: rustup show

      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Check Anvil Installation
        run: |
          if command -v anvil &> /dev/null
          then
              echo "Anvil is installed. Version information:"
              anvil --version
          else
              echo "Anvil is not installed or not in PATH"
              exit 1
          fi

      - name: Clean workspace
        run: |
          cargo llvm-cov clean --workspace

      - name: Run llvm-cov
        env:
          ETHEREUM_BLAST_RPC_URL: ${{ secrets.ETHEREUM_BLAST_RPC_URL }}
        run: |
          cargo llvm-cov nextest --release --lcov --output-path lcov.info --test-threads=1

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          files: lcov.info
          debug: true

      - uses: colpal/actions-clean@v1
        if: ${{ always() }} # To ensure this step runs even when earlier steps fail
