name: E2E test

on:
  workflow_call:

jobs:
  coverage:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack
        env:
          DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID"
          AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY"
        ports:
          - 4566:4566
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3

      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as the cache uses the current rustc version as its cache key
      - run: rustup show

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run e2e test
        run: |
          RUST_LOG=trace SETTLEMENT_LAYER=ethereum_test cargo test --features testing test_orchestrator_workflow -- --nocapture
