---
name: Task - Linters Cargo

on:
  workflow_dispatch:
  workflow_call:

jobs:
  cargo-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as the cache uses the current rustc version as its cache key
      - run: rustup show

      - name: Build SNOS files
        run: |
          # Downloading all the deps
          cargo fetch
          # Navigate to checkouts folder
          cd /home/runner/.cargo/git/checkouts
          # Navigating to snos
          cd snos-*
          # Navigating to the build
          cd 71bd0a1
          # Activating the venv
          source ~/cairo_venv/bin/activate
          # Building the cairo lang repo requirements
          ./scripts/setup-tests.sh

      - uses: Swatinem/rust-cache@v2
      - name: Format and clippy
        run: |
          cargo fmt -- --check
          cargo clippy --no-deps -- -D warnings
          cargo clippy --tests --no-deps -- -D warnings
          cargo clippy --features testing --no-deps -- -D warnings
          cargo clippy --features testing --tests --no-deps -- -D warnings
