---
name: Workflow - Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:

  coverage:
    name: Run coverage
    uses: ./.github/workflows/coverage.yml
