---
name: Workflow - Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  linters:
    name: Run linters
    uses: ./.github/workflows/linters.yml

  rust_build:
    name: Build Rust project
    uses: ./.github/workflows/rust-build.yml

  linters_cargo:
    name: Run Cargo linters
    uses: ./.github/workflows/linters-cargo.yml

  coverage:
    name: Run coverage
    uses: ./.github/workflows/coverage.yml
    needs: rust_build
    secrets: inherit
