---
name: Task - Build Rust

on:
  workflow_dispatch:
  workflow_call:

jobs:
  rust_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: rustup show

      - uses: Swatinem/rust-cache@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Display Python version
        run: python --version

      - name: Install cairo 0
        run: |
          # Creating venv
          python3.9 -m venv ~/cairo_venv
          source ~/cairo_venv/bin/activate

          # Installing deps
          sudo apt install -y libgmp3-dev
          pip3 install ecdsa fastecdsa sympy

          # Installing cairo lang
          pip3 install cairo-lang

      - name: Build SNOS files
        run: |
          python3 -m venv orchestrator_venv
          source orchestrator_venv/bin/activate
          pip install cairo-lang==0.13.2 "sympy<1.13.0"
          mkdir -p build
          git submodule update --init --recursive
          cd cairo-lang
          git checkout a86e92bfde9c171c0856d7b46580c66e004922f3
          cd ..
          cairo-compile cairo-lang/src/starkware/starknet/core/os/os.cairo --output build/os_latest.json --cairo_path cairo-lang/src

      - name: Build the project
        run: |
          cargo build --release --workspace
