---
name: Task - Build Rust

on:
  workflow_dispatch:
  workflow_call:

jobs:
  rust_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: rustup show

      - uses: Swatinem/rust-cache@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Display Python version
        run: python --version

      - name: Install cairo 0
        run: |
          # Creating venv
          python3.9 -m venv ~/cairo_venv
          source ~/cairo_venv/bin/activate

          # Installing deps
          sudo apt install -y libgmp3-dev
          pip3 install ecdsa fastecdsa sympy

          # Installing cairo lang
          pip3 install cairo-lang

      - name: Build SNOS files
        run: |
          # Downloading all the deps
          cargo fetch
          # Navigate to checkouts folder
          cd /home/runner/.cargo/git/checkouts
          # Navigating to snos
          cd snos-*
          # Navigating to the build
          cd 836a4a7
          # Activating the venv
          source ~/cairo_venv/bin/activate
          # Building the cairo lang repo requirements
          ./scripts/setup-tests.sh

      - name: Build the project
        run: |
          cargo build --release --workspace
